### ISSUE TITLE
confusing readme

### ISSUE THREAD

**Issue by Seanmclem** [quangdng/useStateObject#3]
in the readme, you are using useState, not your library? and then one of the items in your array is named useState? 

const [state, **useState**] = **useState**()    ... I don't understand.  

Then later you use setState, without importing it. Is that the library? I feel like the name `setState` is taken. Why not useStateObject?

Also, what happened to useState?

**Comment by quangdng** [comment]
Hey @Seanmclem . Great pick, it was a documentation mistake. It should be 

```
const [state, setState] = useStateObject()
```

instead. I will fix it soon.

**Comment by quangdng** [comment]
Fixed.
